# Generated by Django 3.1.4 on 2020-12-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_auto_20201226_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackStudent',
            new_name='FeedbackStudents',
        ),
        migrations.RenameModel(
            old_name='LeaveReportStaff',
            new_name='LeaveReportStaffs',
        ),
        migrations.RenameModel(
            old_name='LeaveReportStudent',
            new_name='LeaveReportStudents',
        ),
        migrations.RenameModel(
            old_name='NotificationStudent',
            new_name='NotificationStudents',
        ),
    ]
