# Generated by Django 3.1.4 on 2020-12-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0005_auto_20201228_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudents',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
